from reportlab.platypus import Paragraph, Spacer
from .base import create_pdf
from datetime import datetime
from .hashes import generate_hash

def generate_section84_certificate(case, system_name, officer_name, output_path):
    doc, styles = create_pdf(output_path)
    story = []

    story.append(Paragraph("<b>CERTIFICATE OF COMPLIANCE</b>", styles["Title"]))
    story.append(Spacer(1, 12))

    story.append(Paragraph(
        "Pursuant to Section 84 of the Evidence Act, 2011",
        styles["Normal"]
    ))

    story.append(Spacer(1, 12))

    story.append(Paragraph(
        f"I, <b>{officer_name}</b>, certify that the electronic records "
        f"produced in respect of Suit No. <b>{case.suit_number}</b> "
        f"were generated by a computer system operating properly at all material times.",
        styles["Normal"]
    ))

    story.append(Spacer(1, 12))

    story.append(Paragraph(
        f"The system used is identified as <b>{system_name}</b>, "
        "and the information was derived in the ordinary course of its operation.",
        styles["Normal"]
    ))

    story.append(Spacer(1, 24))

    story.append(Paragraph(
        f"Dated this {datetime.now().strftime('%d %B %Y')}",
        styles["Normal"]
    ))

    story.append(Spacer(1, 24))
    story.append(Paragraph("______________________________", styles["Normal"]))
    story.append(Paragraph(f"{officer_name}", styles["Normal"]))
    story.append(Paragraph("Authorized Officer", styles["Normal"]))

    doc.build(story)

    return generate_hash(output_path)
