# Generated by Django 5.2.10 on 2026-01-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourtRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_name', models.CharField(max_length=255)),
                ('rule_title', models.CharField(max_length=255)),
                ('order_number', models.CharField(max_length=50)),
                ('rule_text', models.TextField()),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmallClaimsRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('monetary_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('filing_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allows_lawyers', models.BooleanField()),
                ('procedure_steps', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Statute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('citation', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('jurisdiction', models.CharField(max_length=100)),
                ('full_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
