# Generated by Django 5.2.10 on 2026-01-20 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('court_type', models.CharField(choices=[('SCN', 'Supreme Court'), ('COA', 'Court of Appeal'), ('HCJ', 'High Court of Justice')], max_length=3)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourtCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit_number', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('filing_date', models.DateField()),
                ('sitting_date', models.DateField()),
                ('parties', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courts.court')),
            ],
        ),
        migrations.CreateModel(
            name='CauseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitting_date', models.DateField()),
                ('published_at', models.DateTimeField()),
                ('source_url', models.URLField()),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courts.court')),
                ('courtcases', models.ManyToManyField(related_name='cause_lists', to='courts.courtcase')),
            ],
        ),
        migrations.CreateModel(
            name='Judgment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judgment_date', models.DateField()),
                ('document_url', models.URLField()),
                ('is_final', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True, null=True)),
                ('courtcases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courts.courtcase')),
            ],
        ),
    ]
