# Generated by Django 5.2.10 on 2026-01-20 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courts.courtcase')),
            ],
        ),
        migrations.CreateModel(
            name='CaseSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('plain_english', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courts.courtcase')),
            ],
        ),
        migrations.CreateModel(
            name='PrecedentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_to', to='courts.courtcase')),
                ('source_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searched_from', to='courts.courtcase')),
            ],
        ),
    ]
