# Generated by Django 5.2.10 on 2026-03-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIVideoSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Constitutional', 'Constitutional'), ('Civil', 'Civil'), ('Criminal', 'Criminal')], max_length=50)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('ai_prompt_used', models.TextField(help_text='References to the Nigerian Constitution')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
